name: Update

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * SUN' # every sunday

jobs:
  update:
    name: Pull in latest lib from Nixpkgs
    runs-on: ubuntu-latest
    steps:

    - name: Procure Nix
      uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        path: nixpkgs-lib
        fetch-depth: 0
    
    - name: Checkout nixpkgs repo
      run: |
        git clone https://github.com/NixOS/nixpkgs --branch master --single-branch

    - name: Procure git-filter-repo from nixpkgs
      run: "nix-env -i git-filter-repo -f '<nixpkgs>'"

    - name: Filter nixpkgs on ./nixos/modules/misc
      run: |
        git clone ./nixpkgs nixpkgs-modules
        cd ./nixpkgs-modules
        git filter-repo --path nixos/modules/misc --force

    - name: Filter nixpkgs on ./lib
      run: |
        cd ./nixpkgs
        git filter-repo --path lib --force

    - name: Update nixpkgs.lib
      run: |
        cd ./nixpkgs-lib
        git remote add other ../nixpkgs/
        git remote add modules ../nixpkgs-modules/
        git fetch other master
        git fetch modules master
        export GIT_{COMMITTER,AUTHOR}_EMAIL=41898282+github-actions[bot]@users.noreply.github.com
        export GIT_{COMMITTER,AUTHOR}_NAME=github-actions[bot]
        git merge -X theirs --allow-unrelated-histories other/master
        git merge -X theirs --allow-unrelated-histories modules/master

    - name: Push changes
      run: |
        cd ./nixpkgs-lib
        git push origin master

